// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBou1P9xq6hhzXHZdz8i40Q_FECH3f7nXU',
    appId: '1:17916295900:web:4d0a7814f7ad95a7ff5219',
    messagingSenderId: '17916295900',
    projectId: 'virtualhospitalapp-52c23',
    authDomain: 'virtualhospitalapp-52c23.firebaseapp.com',
    storageBucket: 'virtualhospitalapp-52c23.appspot.com',
    measurementId: 'G-HEEXGJTM67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0tjKkVX1OPfnfLq_1uUuyBLYxfEFXH5k',
    appId: '1:17916295900:android:a1bfdb320a3fb553ff5219',
    messagingSenderId: '17916295900',
    projectId: 'virtualhospitalapp-52c23',
    storageBucket: 'virtualhospitalapp-52c23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzR7R3V3FbUUnfOmCrDpx0rZFtw2W1irc',
    appId: '1:17916295900:ios:3b39f7069cf497a9ff5219',
    messagingSenderId: '17916295900',
    projectId: 'virtualhospitalapp-52c23',
    storageBucket: 'virtualhospitalapp-52c23.appspot.com',
    iosBundleId: 'com.example.virtualHospitalApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzR7R3V3FbUUnfOmCrDpx0rZFtw2W1irc',
    appId: '1:17916295900:ios:3b39f7069cf497a9ff5219',
    messagingSenderId: '17916295900',
    projectId: 'virtualhospitalapp-52c23',
    storageBucket: 'virtualhospitalapp-52c23.appspot.com',
    iosBundleId: 'com.example.virtualHospitalApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBou1P9xq6hhzXHZdz8i40Q_FECH3f7nXU',
    appId: '1:17916295900:web:bfe47c8acba309d9ff5219',
    messagingSenderId: '17916295900',
    projectId: 'virtualhospitalapp-52c23',
    authDomain: 'virtualhospitalapp-52c23.firebaseapp.com',
    storageBucket: 'virtualhospitalapp-52c23.appspot.com',
    measurementId: 'G-NQSQYRL71Q',
  );
}
